## 원하는 단 출력

In [1]:
i,dan=0,0

dan=int(input("단을 입력하세요:"))

for i in range(1,10,1):
    print("%d X %d = %2d"%(dan,i,dan * i))

단을 입력하세요:4
4 X 1 =  4
4 X 2 =  8
4 X 3 = 12
4 X 4 = 16
4 X 5 = 20
4 X 6 = 24
4 X 7 = 28
4 X 8 = 32
4 X 9 = 36

## 원하는 단 출력(역순)

In [2]:
i,dan=0,0

dan=int(input("단을 입력하세요:"))

for i in range(9,0,-1):
    print("%d X %d = %2d"%(i,dan,dan * i))

단을 입력하세요:45
9 X 45 = 405
8 X 45 = 360
7 X 45 = 315
6 X 45 = 270
5 X 45 = 225
4 X 45 = 180
3 X 45 = 135
2 X 45 = 90
1 X 45 = 45

In [3]:
i,k=0,0

for i in range(2,10,1):
    for k in range(1,10,1):
        print("%d X %d = %2d"%(i,k,i * k))
        
        print("")

2 X 1 =  2

2 X 2 =  4

2 X 3 =  6

2 X 4 =  8

2 X 5 = 10

2 X 6 = 12

2 X 7 = 14

2 X 8 = 16

2 X 9 = 18

3 X 1 =  3

3 X 2 =  6

3 X 3 =  9

3 X 4 = 12

3 X 5 = 15

3 X 6 = 18

3 X 7 = 21

3 X 8 = 24

3 X 9 = 27

4 X 1 =  4

4 X 2 =  8

4 X 3 = 12

4 X 4 = 16

4 X 5 = 20

4 X 6 = 24

4 X 7 = 28

4 X 8 = 32

4 X 9 = 36

5 X 1 =  5

5 X 2 = 10

5 X 3 = 15

5 X 4 = 20

5 X 5 = 25

5 X 6 = 30

5 X 7 = 35

5 X 8 = 40

5 X 9 = 45

6 X 1 =  6

6 X 2 = 12

6 X 3 = 18

6 X 4 = 24

6 X 5 = 30

6 X 6 = 36

6 X 7 = 42

6 X 8 = 48

6 X 9 = 54

7 X 1 =  7

7 X 2 = 14

7 X 3 = 21

7 X 4 = 28

7 X 5 = 35

7 X 6 = 42

7 X 7 = 49

7 X 8 = 56

7 X 9 = 63

8 X 1 =  8

8 X 2 = 16

8 X 3 = 24

8 X 4 = 32

8 X 5 = 40

8 X 6 = 48

8 X 7 = 56

8 X 8 = 64

8 X 9 = 72

9 X 1 =  9

9 X 2 = 18

9 X 3 = 27

9 X 4 = 36

9 X 5 = 45

9 X 6 = 54

9 X 7 = 63

9 X 8 = 72

9 X 9 = 81

In [4]:
i,k=0,0

for i in range(2,10,1):
    print("##  %d단  ##"%i)
    for k in range(1,10,1):
        print("%d X %d = %2d"%(i,k,i * k))
        
        print("")

##  2단  ##
2 X 1 =  2

2 X 2 =  4

2 X 3 =  6

2 X 4 =  8

2 X 5 = 10

2 X 6 = 12

2 X 7 = 14

2 X 8 = 16

2 X 9 = 18

##  3단  ##
3 X 1 =  3

3 X 2 =  6

3 X 3 =  9

3 X 4 = 12

3 X 5 = 15

3 X 6 = 18

3 X 7 = 21

3 X 8 = 24

3 X 9 = 27

##  4단  ##
4 X 1 =  4

4 X 2 =  8

4 X 3 = 12

4 X 4 = 16

4 X 5 = 20

4 X 6 = 24

4 X 7 = 28

4 X 8 = 32

4 X 9 = 36

##  5단  ##
5 X 1 =  5

5 X 2 = 10

5 X 3 = 15

5 X 4 = 20

5 X 5 = 25

5 X 6 = 30

5 X 7 = 35

5 X 8 = 40

5 X 9 = 45

##  6단  ##
6 X 1 =  6

6 X 2 = 12

6 X 3 = 18

6 X 4 = 24

6 X 5 = 30

6 X 6 = 36

6 X 7 = 42

6 X 8 = 48

6 X 9 = 54

##  7단  ##
7 X 1 =  7

7 X 2 = 14

7 X 3 = 21

7 X 4 = 28

7 X 5 = 35

7 X 6 = 42

7 X 7 = 49

7 X 8 = 56

7 X 9 = 63

##  8단  ##
8 X 1 =  8

8 X 2 = 16

8 X 3 = 24

8 X 4 = 32

8 X 5 = 40

8 X 6 = 48

8 X 7 = 56

8 X 8 = 64

8 X 9 = 72

##  9단  ##
9 X 1 =  9

9 X 2 = 18

9 X 3 = 27

9 X 4 = 36

9 X 5 = 45

9 X 6 = 54

9 X 7 = 63

9 X 8 = 72

9 X 9 = 81

In [5]:
#중첩 for문

i,k ,gu=0,0,""

for i in range(2,10):
    gu=gu+("# %d단 # "%i)
    
print(gu)

for i in range(1,10):
    gu=""
    for k in range(2,10):
        gu=gu+str("%2dX%2d=%2d"%(k,i,k*i))
        
    print(gu)

# 2단 # # 3단 # # 4단 # # 5단 # # 6단 # # 7단 # # 8단 # # 9단 #
 2X 1= 2 3X 1= 3 4X 1= 4 5X 1= 5 6X 1= 6 7X 1= 7 8X 1= 8 9X 1= 9
 2X 2= 4 3X 2= 6 4X 2= 8 5X 2=10 6X 2=12 7X 2=14 8X 2=16 9X 2=18
 2X 3= 6 3X 3= 9 4X 3=12 5X 3=15 6X 3=18 7X 3=21 8X 3=24 9X 3=27
 2X 4= 8 3X 4=12 4X 4=16 5X 4=20 6X 4=24 7X 4=28 8X 4=32 9X 4=36
 2X 5=10 3X 5=15 4X 5=20 5X 5=25 6X 5=30 7X 5=35 8X 5=40 9X 5=45
 2X 6=12 3X 6=18 4X 6=24 5X 6=30 6X 6=36 7X 6=42 8X 6=48 9X 6=54
 2X 7=14 3X 7=21 4X 7=28 5X 7=35 6X 7=42 7X 7=49 8X 7=56 9X 7=63
 2X 8=16 3X 8=24 4X 8=32 5X 8=40 6X 8=48 7X 8=56 8X 8=64 9X 8=72
 2X 9=18 3X 9=27 4X 9=36 5X 9=45 6X 9=54 7X 9=63 8X 9=72 9X 9=81

In [6]:
#중첩 for문

i,k ,gu=0,0,""

for i in range(9,1,-1):
    gu=gu+("# %d단 # "%i)
    
print(gu)

for i in range(9,0,-1):
    gu=""
    for k in range(9,1,-1):
        gu=gu+str("%2dX%2d=%2d"%(k,i,k*i))
        
    print(gu)

# 9단 # # 8단 # # 7단 # # 6단 # # 5단 # # 4단 # # 3단 # # 2단 #
 9X 9=81 8X 9=72 7X 9=63 6X 9=54 5X 9=45 4X 9=36 3X 9=27 2X 9=18
 9X 8=72 8X 8=64 7X 8=56 6X 8=48 5X 8=40 4X 8=32 3X 8=24 2X 8=16
 9X 7=63 8X 7=56 7X 7=49 6X 7=42 5X 7=35 4X 7=28 3X 7=21 2X 7=14
 9X 6=54 8X 6=48 7X 6=42 6X 6=36 5X 6=30 4X 6=24 3X 6=18 2X 6=12
 9X 5=45 8X 5=40 7X 5=35 6X 5=30 5X 5=25 4X 5=20 3X 5=15 2X 5=10
 9X 4=36 8X 4=32 7X 4=28 6X 4=24 5X 4=20 4X 4=16 3X 4=12 2X 4= 8
 9X 3=27 8X 3=24 7X 3=21 6X 3=18 5X 3=15 4X 3=12 3X 3= 9 2X 3= 6
 9X 2=18 8X 2=16 7X 2=14 6X 2=12 5X 2=10 4X 2= 8 3X 2= 6 2X 2= 4
 9X 1= 9 8X 1= 8 7X 1= 7 6X 1= 6 5X 1= 5 4X 1= 4 3X 1= 3 2X 1= 2